export const GET_INITIAL_TIMEZONES = 'GET_INITIAL_TIMEZONES';
export const ADD_TIMEZONE = 'ADD_TIMEZONE';
export const UPDATE_TIMEZONE = 'UPDATE_TIMEZONE';
export const REMOVE_TIMEZONE = 'REMOVE_TIMEZONE';
export const EDIT_TIMEZONE = 'EDIT_TIMEZONE';

export default {
    GET_INITIAL_TIMEZONES,
    ADD_TIMEZONE,
    UPDATE_TIMEZONE,
    REMOVE_TIMEZONE,
    EDIT_TIMEZONE,
}